version: '2.3'
services:
  allinone:
    image: ghcr.io/wy580477/aria2-aio-container:latest
    container_name: allinone
    network_mode: host
    # host模式配置方便，性能好问题少，如果host上没有其他敏感服务，建议使用host模式。
    logging:
      driver: "journald"
      # 个人偏好journald自动管理日志，journalctl查询起来也方便。     
      options:
        tag: "{{.Name}}"
        # 给日志添加容器名的tag。
    environment:
      - USER=admin
      # 用户名
      - PASSWORD=password
      # 务必设置为强密码
      - DOMAIN=
      # 域名设置为有效域名（可以解析到你的host）,并且80和443端口面向公网开放，就可启用caddy的自动申请证书开启https功能。
      # 设置为http://localhost，则监听本地回环地址提供http服务。
      # 设置为空值，则对外部ip开放http服务，不建议在家庭局域网以外的环境使用。
      - EMAIL=internal
      # 接受证书颁发机构通知邮件的地址，可以填虚假地址。
      # 默认值internal为使用caddy自签证书。
      - WEB_PORT=8080
      # 提供Web服务的端口，如果要关闭caddy自动https功能，需设置为非443端口。
      - PORTAL_PATH=/portal
      # 基础URL，后面不能加/。建议设置为不常见的字符串，防止字典爆破攻击。
      # 不需要基础URL的话，设置为空值，不能设置为/。
      - LANGUAGE=chs
      # 设置导航页和Filebrowser界面语言为中文，可选en（英文）。
      - POST_MODE=move_remote
      # Aria2自动化模式，move_remote模式为下载做种完成后先移动到本地data数据卷下finished目录，然后移动到rclone远程存储。
      # copy_remote_first模式为下载完成后立即复制到rclone原创存储，BT任务在做种前即触发。更多模式见详细部署指南。
    restart: unless-stopped
    volumes:
      - ~/data:/mnt/data
      # 下载数据存放目录。将~/data换成你在host上想指定的目录。
      - allinone_conf:/mnt/config
      # 配置文件存放目录，这里使用了volume功能，也可以和上面data目录一样用bind mount方式挂载。
volumes:
  allinone_conf:
