version: '3.4'
x-global: &global
# 全局设置
  environment: 
    - PUID=0
    - PGID=0
    # 设置用户uid和gid，如需以非特权用户运行容器内进程，设置为1000以上即可，注意data目录下如果之前有子目录，权限需要手动设置。
  volumes:
    - ~/data:/mnt/data
    # 下载数据存放目录。将~/data换成你在host上想指定的目录。
    - ~/config:/mnt/config
    # 配置文件存放目录。将~/config换成你在host上想指定的目录。
  restart: unless-stopped
  logging:
      driver: "journald"
      # 个人偏好journald自动管理日志，journalctl查询起来也方便。     
      options:
        tag: "{{.Name}}"
        # 给日志添加容器名(container_name)的tag。   
services:
  allinone:
    <<: *global
    image: ghcr.io/wy580477/aria2-aio-container:latest
    container_name: allinone
    network_mode: host
    # host模式配置方便，不容易出问题。如果追求更安全，则需要配置bridge模式映射端口。
    environment: 
      - USER=admin
      # 用户名
      - PASSWORD=password
      # 务必设置为强密码
      - DOMAIN=
      # 域名设置为有效域名（可以解析到你的host）,并且80和443端口面向公网开放，就可启用caddy的自动申请证书开启https功能。
      # 设置为http://localhost，则监听本地回环地址提供http服务。
      # 设置为空值，则对外部ip开放http服务，不建议在家庭局域网以外的环境使用。
      - EMAIL=internal
      # 接受证书颁发机构通知邮件的地址，可以填虚假地址。
      # 默认值internal为使用caddy自签证书。
      - WEB_PORT=8080
      # 提供Web服务的端口，如果要关闭caddy自动https功能，需设置为非443端口。
      - LANGUAGE=chs
      # 设置导航页和Filebrowser界面语言为中文，可选en（英文）。
      - PORTAL_PATH=/portal
      # 基础URL，后面不能加/。建议设置为不常见的字符串，防止字典爆破攻击。
      # 不需要基础URL的话，设置为空值，不能设置为/。
      - ARIA_IPV6=false
      # Aria2下载ipv6开关，不影响其他进程使用ipv6网络。
      - BT_PORT=51413
      # Aria2 BT下载使用的端口，建议在防火墙设置中tcp和udp流量都放行，以提高下载速度。
      - POST_MODE=move_remote
      # Aria2自动化模式，dummy模式为无操作，move模式为下载及做种完成后移动到本地finished目录。
      # move_remote模式为下载及做种完成后先移动到本地data数据卷下finished目录，然后移动到rclone远程存储。
      # move_remote_only模式为下载及做种完成后移动到rclone原创存储。
      # copy_remote_first模式为下载完成后立即复制到rclone原创存储，BT任务在做种前即触发。
      # copy_remote模式为下载及做种完成后先移动到本地data数据卷下finished目录，然后复制到rclone远程存储。
      # custom模式为自行设置aria2配置文件触发脚本选项。
      - AUTO_DRIVE_NAME=true
      # Rclone远程存储配置名称，默认值auto会从rclone.conf文件第一行中提取远程存储配置名称。
      - CLEAN_UNFINISHED_FAILED_TASK_FILES=true
      # 删除失败和在下载完成之前移除的任务文件。
  allinone_rclone:
    <<: *global
    image: rclone/rclone
    container_name: allineone_rclone
    ports:
      - "127.0.0.1:56802:5572"